// Create mock for audit-log module
export const createAuditLog = jest.fn();

export const AUDIT_ACTIONS = {
  CREATE_TOURNAMENT: 'CREATE_TOURNAMENT',
  UPDATE_TOURNAMENT: 'UPDATE_TOURNAMENT',
  DELETE_TOURNAMENT: 'DELETE_TOURNAMENT',
  CREATE_PLAYER: 'CREATE_PLAYER',
  UPDATE_PLAYER: 'UPDATE_PLAYER',
  DELETE_PLAYER: 'DELETE_PLAYER',
  CREATE_TA_ENTRY: 'CREATE_TA_ENTRY',
  UPDATE_TA_ENTRY: 'UPDATE_TA_ENTRY',
  DELETE_TA_ENTRY: 'DELETE_TA_ENTRY',
  CREATE_BM_MATCH: 'CREATE_BM_MATCH',
  UPDATE_BM_MATCH: 'UPDATE_BM_MATCH',
  DELETE_BM_MATCH: 'DELETE_BM_MATCH',
  CREATE_MR_MATCH: 'CREATE_MR_MATCH',
  UPDATE_MR_MATCH: 'UPDATE_MR_MATCH',
  DELETE_MR_MATCH: 'DELETE_MR_MATCH',
  CREATE_BRACKET: 'CREATE_BRACKET',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  UNAUTHORIZED_ACCESS: 'UNAUTHORIZED_ACCESS',
} as const;
