/**
 * ISO 3166-1 alpha-2 country list with English + Japanese names.
 *
 * GENERATED — do not edit the COUNTRIES array by hand. Regenerate with
 * `node scripts/gen-countries.cjs` (uses i18n-iso-countries + country-flag-icons).
 * Only codes that have an SVG flag in country-flag-icons are included, so every
 * entry is guaranteed renderable by <CountryFlag/>.
 */

export interface Country {
  /** ISO 3166-1 alpha-2 code, uppercase (e.g. "JP"). */
  code: string;
  /** English country name. */
  en: string;
  /** Japanese country name. */
  ja: string;
}

export const COUNTRIES: readonly Country[] = [
  { code: "AF", en: "Afghanistan", ja: "アフガニスタン" },
  { code: "AX", en: "Åland Islands", ja: "オーランド諸島" },
  { code: "AL", en: "Albania", ja: "アルバニア" },
  { code: "DZ", en: "Algeria", ja: "アルジェリア" },
  { code: "AS", en: "American Samoa", ja: "アメリカ領サモア" },
  { code: "AD", en: "Andorra", ja: "アンドラ" },
  { code: "AO", en: "Angola", ja: "アンゴラ" },
  { code: "AI", en: "Anguilla", ja: "アンギラ" },
  { code: "AQ", en: "Antarctica", ja: "南極" },
  { code: "AG", en: "Antigua and Barbuda", ja: "アンティグア・バーブーダ" },
  { code: "AR", en: "Argentina", ja: "アルゼンチン" },
  { code: "AM", en: "Armenia", ja: "アルメニア" },
  { code: "AW", en: "Aruba", ja: "アルバ" },
  { code: "AU", en: "Australia", ja: "オーストラリア" },
  { code: "AT", en: "Austria", ja: "オーストリア" },
  { code: "AZ", en: "Azerbaijan", ja: "アゼルバイジャン" },
  { code: "BS", en: "Bahamas", ja: "バハマ" },
  { code: "BH", en: "Bahrain", ja: "バーレーン" },
  { code: "BD", en: "Bangladesh", ja: "バングラデシュ" },
  { code: "BB", en: "Barbados", ja: "バルバドス" },
  { code: "BY", en: "Belarus", ja: "ベラルーシ" },
  { code: "BE", en: "Belgium", ja: "ベルギー" },
  { code: "BZ", en: "Belize", ja: "ベリーズ" },
  { code: "BJ", en: "Benin", ja: "ベナン" },
  { code: "BM", en: "Bermuda", ja: "バミューダ" },
  { code: "BT", en: "Bhutan", ja: "ブータン" },
  { code: "BO", en: "Bolivia", ja: "ボリビア多民族国" },
  { code: "BQ", en: "Bonaire, Sint Eustatius and Saba", ja: "ボネール、シント・ユースタティウスおよびサバ" },
  { code: "BA", en: "Bosnia and Herzegovina", ja: "ボスニア・ヘルツェゴビナ" },
  { code: "BW", en: "Botswana", ja: "ボツワナ" },
  { code: "BV", en: "Bouvet Island", ja: "ブーベ島" },
  { code: "BR", en: "Brazil", ja: "ブラジル" },
  { code: "IO", en: "British Indian Ocean Territory", ja: "イギリス領インド洋地域" },
  { code: "BN", en: "Brunei Darussalam", ja: "ブルネイ・ダルサラーム" },
  { code: "BG", en: "Bulgaria", ja: "ブルガリア" },
  { code: "BF", en: "Burkina Faso", ja: "ブルキナファソ" },
  { code: "BI", en: "Burundi", ja: "ブルンジ" },
  { code: "KH", en: "Cambodia", ja: "カンボジア" },
  { code: "CM", en: "Cameroon", ja: "カメルーン" },
  { code: "CA", en: "Canada", ja: "カナダ" },
  { code: "CV", en: "Cape Verde", ja: "カーボベルデ" },
  { code: "KY", en: "Cayman Islands", ja: "ケイマン諸島" },
  { code: "CF", en: "Central African Republic", ja: "中央アフリカ共和国" },
  { code: "TD", en: "Chad", ja: "チャド" },
  { code: "CL", en: "Chile", ja: "チリ" },
  { code: "CX", en: "Christmas Island", ja: "クリスマス島" },
  { code: "CC", en: "Cocos (Keeling) Islands", ja: "ココス（キーリング）諸島" },
  { code: "CO", en: "Colombia", ja: "コロンビア" },
  { code: "KM", en: "Comoros", ja: "コモロ" },
  { code: "CK", en: "Cook Islands", ja: "クック諸島" },
  { code: "CR", en: "Costa Rica", ja: "コスタリカ" },
  { code: "CI", en: "Cote d'Ivoire", ja: "コートジボワール" },
  { code: "HR", en: "Croatia", ja: "クロアチア" },
  { code: "CU", en: "Cuba", ja: "キューバ" },
  { code: "CW", en: "Curaçao", ja: "キュラソー" },
  { code: "CY", en: "Cyprus", ja: "キプロス" },
  { code: "CZ", en: "Czech Republic", ja: "チェコ" },
  { code: "CD", en: "Democratic Republic of the Congo", ja: "コンゴ民主共和国" },
  { code: "DK", en: "Denmark", ja: "デンマーク" },
  { code: "DJ", en: "Djibouti", ja: "ジブチ" },
  { code: "DM", en: "Dominica", ja: "ドミニカ国" },
  { code: "DO", en: "Dominican Republic", ja: "ドミニカ共和国" },
  { code: "EC", en: "Ecuador", ja: "エクアドル" },
  { code: "EG", en: "Egypt", ja: "エジプト" },
  { code: "SV", en: "El Salvador", ja: "エルサルバドル" },
  { code: "GQ", en: "Equatorial Guinea", ja: "赤道ギニア" },
  { code: "ER", en: "Eritrea", ja: "エリトリア" },
  { code: "EE", en: "Estonia", ja: "エストニア" },
  { code: "SZ", en: "Eswatini", ja: "スワジランド" },
  { code: "ET", en: "Ethiopia", ja: "エチオピア" },
  { code: "FK", en: "Falkland Islands (Malvinas)", ja: "フォークランド（マルビナス）諸島" },
  { code: "FO", en: "Faroe Islands", ja: "フェロー諸島" },
  { code: "FJ", en: "Fiji", ja: "フィジー" },
  { code: "FI", en: "Finland", ja: "フィンランド" },
  { code: "FR", en: "France", ja: "フランス" },
  { code: "GF", en: "French Guiana", ja: "フランス領ギアナ" },
  { code: "PF", en: "French Polynesia", ja: "フランス領ポリネシア" },
  { code: "TF", en: "French Southern Territories", ja: "フランス領南方・南極地域" },
  { code: "GA", en: "Gabon", ja: "ガボン" },
  { code: "GE", en: "Georgia", ja: "ジョージア" },
  { code: "DE", en: "Germany", ja: "ドイツ" },
  { code: "GH", en: "Ghana", ja: "ガーナ" },
  { code: "GI", en: "Gibraltar", ja: "ジブラルタル" },
  { code: "GR", en: "Greece", ja: "ギリシャ" },
  { code: "GL", en: "Greenland", ja: "グリーンランド" },
  { code: "GD", en: "Grenada", ja: "グレナダ" },
  { code: "GP", en: "Guadeloupe", ja: "グアドループ" },
  { code: "GU", en: "Guam", ja: "グアム" },
  { code: "GT", en: "Guatemala", ja: "グアテマラ" },
  { code: "GG", en: "Guernsey", ja: "ガーンジー" },
  { code: "GN", en: "Guinea", ja: "ギニア" },
  { code: "GW", en: "Guinea-Bissau", ja: "ギニアビサウ" },
  { code: "GY", en: "Guyana", ja: "ガイアナ" },
  { code: "HT", en: "Haiti", ja: "ハイチ" },
  { code: "HM", en: "Heard Island and McDonald Islands", ja: "ハード島とマクドナルド諸島" },
  { code: "VA", en: "Holy See (Vatican City State)", ja: "バチカン市国" },
  { code: "HN", en: "Honduras", ja: "ホンジュラス" },
  { code: "HK", en: "Hong Kong", ja: "香港" },
  { code: "HU", en: "Hungary", ja: "ハンガリー" },
  { code: "IS", en: "Iceland", ja: "アイスランド" },
  { code: "IN", en: "India", ja: "インド" },
  { code: "ID", en: "Indonesia", ja: "インドネシア" },
  { code: "IQ", en: "Iraq", ja: "イラク" },
  { code: "IE", en: "Ireland", ja: "アイルランド" },
  { code: "IR", en: "Islamic Republic of Iran", ja: "イラン・イスラム共和国" },
  { code: "IM", en: "Isle of Man", ja: "マン島" },
  { code: "IL", en: "Israel", ja: "イスラエル" },
  { code: "IT", en: "Italy", ja: "イタリア" },
  { code: "JM", en: "Jamaica", ja: "ジャマイカ" },
  { code: "JP", en: "Japan", ja: "日本" },
  { code: "JE", en: "Jersey", ja: "ジャージー" },
  { code: "JO", en: "Jordan", ja: "ヨルダン" },
  { code: "KZ", en: "Kazakhstan", ja: "カザフスタン" },
  { code: "KE", en: "Kenya", ja: "ケニア" },
  { code: "KI", en: "Kiribati", ja: "キリバス" },
  { code: "XK", en: "Kosovo", ja: "コソボ" },
  { code: "KW", en: "Kuwait", ja: "クウェート" },
  { code: "KG", en: "Kyrgyzstan", ja: "キルギス" },
  { code: "LA", en: "Lao People's Democratic Republic", ja: "ラオス人民民主共和国" },
  { code: "LV", en: "Latvia", ja: "ラトビア" },
  { code: "LB", en: "Lebanon", ja: "レバノン" },
  { code: "LS", en: "Lesotho", ja: "レソト" },
  { code: "LR", en: "Liberia", ja: "リベリア" },
  { code: "LY", en: "Libya", ja: "リビア" },
  { code: "LI", en: "Liechtenstein", ja: "リヒテンシュタイン" },
  { code: "LT", en: "Lithuania", ja: "リトアニア" },
  { code: "LU", en: "Luxembourg", ja: "ルクセンブルク" },
  { code: "MO", en: "Macao", ja: "マカオ" },
  { code: "MG", en: "Madagascar", ja: "マダガスカル" },
  { code: "MW", en: "Malawi", ja: "マラウイ" },
  { code: "MY", en: "Malaysia", ja: "マレーシア" },
  { code: "MV", en: "Maldives", ja: "モルディブ" },
  { code: "ML", en: "Mali", ja: "マリ" },
  { code: "MT", en: "Malta", ja: "マルタ" },
  { code: "MH", en: "Marshall Islands", ja: "マーシャル諸島" },
  { code: "MQ", en: "Martinique", ja: "マルティニーク" },
  { code: "MR", en: "Mauritania", ja: "モーリタニア" },
  { code: "MU", en: "Mauritius", ja: "モーリシャス" },
  { code: "YT", en: "Mayotte", ja: "マヨット" },
  { code: "MX", en: "Mexico", ja: "メキシコ" },
  { code: "FM", en: "Micronesia, Federated States of", ja: "ミクロネシア連邦" },
  { code: "MD", en: "Moldova, Republic of", ja: "モルドバ共和国" },
  { code: "MC", en: "Monaco", ja: "モナコ" },
  { code: "MN", en: "Mongolia", ja: "モンゴル" },
  { code: "ME", en: "Montenegro", ja: "モンテネグロ" },
  { code: "MS", en: "Montserrat", ja: "モントセラト" },
  { code: "MA", en: "Morocco", ja: "モロッコ" },
  { code: "MZ", en: "Mozambique", ja: "モザンビーク" },
  { code: "MM", en: "Myanmar", ja: "ミャンマー" },
  { code: "NA", en: "Namibia", ja: "ナミビア" },
  { code: "NR", en: "Nauru", ja: "ナウル" },
  { code: "NP", en: "Nepal", ja: "ネパール" },
  { code: "NL", en: "Netherlands", ja: "オランダ" },
  { code: "NC", en: "New Caledonia", ja: "ニューカレドニア" },
  { code: "NZ", en: "New Zealand", ja: "ニュージーランド" },
  { code: "NI", en: "Nicaragua", ja: "ニカラグア" },
  { code: "NE", en: "Niger", ja: "ニジェール" },
  { code: "NG", en: "Nigeria", ja: "ナイジェリア" },
  { code: "NU", en: "Niue", ja: "ニウエ" },
  { code: "NF", en: "Norfolk Island", ja: "ノーフォーク島" },
  { code: "KP", en: "North Korea", ja: "朝鮮民主主義人民共和国" },
  { code: "MP", en: "Northern Mariana Islands", ja: "北マリアナ諸島" },
  { code: "NO", en: "Norway", ja: "ノルウェー" },
  { code: "OM", en: "Oman", ja: "オマーン" },
  { code: "PK", en: "Pakistan", ja: "パキスタン" },
  { code: "PW", en: "Palau", ja: "パラオ" },
  { code: "PA", en: "Panama", ja: "パナマ" },
  { code: "PG", en: "Papua New Guinea", ja: "パプアニューギニア" },
  { code: "PY", en: "Paraguay", ja: "パラグアイ" },
  { code: "CN", en: "People's Republic of China", ja: "中華人民共和国" },
  { code: "PE", en: "Peru", ja: "ペルー" },
  { code: "PH", en: "Philippines", ja: "フィリピン" },
  { code: "PN", en: "Pitcairn", ja: "ピトケアン" },
  { code: "PL", en: "Poland", ja: "ポーランド" },
  { code: "PT", en: "Portugal", ja: "ポルトガル" },
  { code: "PR", en: "Puerto Rico", ja: "プエルトリコ" },
  { code: "QA", en: "Qatar", ja: "カタール" },
  { code: "CG", en: "Republic of the Congo", ja: "コンゴ共和国" },
  { code: "GM", en: "Republic of The Gambia", ja: "ガンビア" },
  { code: "RE", en: "Reunion", ja: "レユニオン" },
  { code: "RO", en: "Romania", ja: "ルーマニア" },
  { code: "RU", en: "Russian Federation", ja: "ロシア連邦" },
  { code: "RW", en: "Rwanda", ja: "ルワンダ" },
  { code: "BL", en: "Saint Barthélemy", ja: "サン・バルテルミー" },
  { code: "SH", en: "Saint Helena", ja: "セントヘレナ・アセンションおよびトリスタンダクーニャ" },
  { code: "KN", en: "Saint Kitts and Nevis", ja: "セントクリストファー・ネイビス" },
  { code: "LC", en: "Saint Lucia", ja: "セントルシア" },
  { code: "MF", en: "Saint Martin (French part)", ja: "サン・マルタン（フランス領）" },
  { code: "PM", en: "Saint Pierre and Miquelon", ja: "サンピエール島・ミクロン島" },
  { code: "VC", en: "Saint Vincent and the Grenadines", ja: "セントビンセントおよびグレナディーン諸島" },
  { code: "WS", en: "Samoa", ja: "サモア" },
  { code: "SM", en: "San Marino", ja: "サンマリノ" },
  { code: "ST", en: "Sao Tome and Principe", ja: "サントメ・プリンシペ" },
  { code: "SA", en: "Saudi Arabia", ja: "サウジアラビア" },
  { code: "SN", en: "Senegal", ja: "セネガル" },
  { code: "RS", en: "Serbia", ja: "セルビア" },
  { code: "SC", en: "Seychelles", ja: "セーシェル" },
  { code: "SL", en: "Sierra Leone", ja: "シエラレオネ" },
  { code: "SG", en: "Singapore", ja: "シンガポール" },
  { code: "SX", en: "Sint Maarten (Dutch part)", ja: "シント・マールテン（オランダ領）" },
  { code: "SK", en: "Slovakia", ja: "スロバキア" },
  { code: "SI", en: "Slovenia", ja: "スロベニア" },
  { code: "SB", en: "Solomon Islands", ja: "ソロモン諸島" },
  { code: "SO", en: "Somalia", ja: "ソマリア" },
  { code: "ZA", en: "South Africa", ja: "南アフリカ" },
  { code: "GS", en: "South Georgia and the South Sandwich Islands", ja: "サウスジョージア・サウスサンドウィッチ諸島" },
  { code: "KR", en: "South Korea", ja: "大韓民国" },
  { code: "SS", en: "South Sudan", ja: "南スーダン" },
  { code: "ES", en: "Spain", ja: "スペイン" },
  { code: "LK", en: "Sri Lanka", ja: "スリランカ" },
  { code: "PS", en: "State of Palestine", ja: "パレスチナ" },
  { code: "SD", en: "Sudan", ja: "スーダン" },
  { code: "SR", en: "Suriname", ja: "スリナム" },
  { code: "SJ", en: "Svalbard and Jan Mayen", ja: "スヴァールバル諸島およびヤンマイエン島" },
  { code: "SE", en: "Sweden", ja: "スウェーデン" },
  { code: "CH", en: "Switzerland", ja: "スイス" },
  { code: "SY", en: "Syrian Arab Republic", ja: "シリア・アラブ共和国" },
  { code: "TW", en: "Taiwan, Province of China", ja: "台湾" },
  { code: "TJ", en: "Tajikistan", ja: "タジキスタン" },
  { code: "TH", en: "Thailand", ja: "タイ" },
  { code: "MK", en: "The Republic of North Macedonia", ja: "北マケドニア" },
  { code: "TL", en: "Timor-Leste", ja: "東ティモール" },
  { code: "TG", en: "Togo", ja: "トーゴ" },
  { code: "TK", en: "Tokelau", ja: "トケラウ" },
  { code: "TO", en: "Tonga", ja: "トンガ" },
  { code: "TT", en: "Trinidad and Tobago", ja: "トリニダード・トバゴ" },
  { code: "TN", en: "Tunisia", ja: "チュニジア" },
  { code: "TR", en: "Türkiye", ja: "トルコ" },
  { code: "TM", en: "Turkmenistan", ja: "トルクメニスタン" },
  { code: "TC", en: "Turks and Caicos Islands", ja: "タークス・カイコス諸島" },
  { code: "TV", en: "Tuvalu", ja: "ツバル" },
  { code: "UG", en: "Uganda", ja: "ウガンダ" },
  { code: "UA", en: "Ukraine", ja: "ウクライナ" },
  { code: "AE", en: "United Arab Emirates", ja: "アラブ首長国連邦" },
  { code: "GB", en: "United Kingdom", ja: "イギリス" },
  { code: "TZ", en: "United Republic of Tanzania", ja: "タンザニア" },
  { code: "UM", en: "United States Minor Outlying Islands", ja: "合衆国領有小離島" },
  { code: "US", en: "United States of America", ja: "アメリカ合衆国" },
  { code: "UY", en: "Uruguay", ja: "ウルグアイ" },
  { code: "UZ", en: "Uzbekistan", ja: "ウズベキスタン" },
  { code: "VU", en: "Vanuatu", ja: "バヌアツ" },
  { code: "VE", en: "Venezuela", ja: "ベネズエラ・ボリバル共和国" },
  { code: "VN", en: "Vietnam", ja: "ベトナム" },
  { code: "VG", en: "Virgin Islands, British", ja: "イギリス領ヴァージン諸島" },
  { code: "VI", en: "Virgin Islands, U.S.", ja: "アメリカ領ヴァージン諸島" },
  { code: "WF", en: "Wallis and Futuna", ja: "ウォリス・フツナ" },
  { code: "EH", en: "Western Sahara", ja: "西サハラ" },
  { code: "YE", en: "Yemen", ja: "イエメン" },
  { code: "ZM", en: "Zambia", ja: "ザンビア" },
  { code: "ZW", en: "Zimbabwe", ja: "ジンバブエ" },
];

const BY_CODE = new Map(COUNTRIES.map((c) => [c.code, c]));
// Lowercased English/Japanese name -> code, so legacy free-text country values
// (the DB historically stored full names like "Norway") still resolve to a flag.
const BY_NAME = new Map<string, string>();
for (const c of COUNTRIES) {
  BY_NAME.set(c.en.toLowerCase(), c.code);
  BY_NAME.set(c.ja.toLowerCase(), c.code);
}

/** Look up a country by its ISO alpha-2 code (case-insensitive). */
export function getCountry(code: string | null | undefined): Country | undefined {
  if (!code) return undefined;
  return BY_CODE.get(code.trim().toUpperCase());
}

/**
 * Resolve an arbitrary stored country value to its ISO alpha-2 code. Accepts an
 * ISO code ("NO", "no") or a full English/Japanese name ("Norway", "ノルウェー"),
 * so both the new picker values and historical free-text values map to a flag.
 * Returns undefined when nothing matches (caller renders no flag).
 */
export function resolveCountryCode(
  value: string | null | undefined,
): string | undefined {
  if (!value) return undefined;
  const v = value.trim();
  if (!v) return undefined;
  const upper = v.toUpperCase();
  if (BY_CODE.has(upper)) return upper;
  return BY_NAME.get(v.toLowerCase());
}

/** Localized country name for a code, falling back to English then the code. */
export function getCountryName(
  code: string | null | undefined,
  locale: string,
): string | undefined {
  const c = getCountry(code);
  if (!c) return undefined;
  return locale.startsWith("ja") ? c.ja : c.en;
}
