/**
 * QR Login Token Utilities (issue #3055)
 *
 * Generates and hashes the bearer token embedded in a player's QR login
 * code. This is intentionally NOT bcrypt (see password-utils.ts):
 * QR sign-in only has the raw token, not the player's identity, so the
 * database must be searchable by hash value (`Player.qrLoginTokenHash`
 * is a unique index). Bcrypt's per-hash random salt makes that kind of
 * lookup impossible.
 *
 * SHA-256 is safe here specifically because the input is a 256-bit
 * cryptographically random value generated by this module, not a
 * low-entropy user-chosen secret like a password. There is no
 * dictionary/rainbow-table surface to defend against with a slow hash —
 * only brute force over the full random keyspace, which is infeasible.
 */

const TOKEN_BYTES = 32; // 256 bits of entropy, matches typical bearer-token sizing

function base64UrlEncode(bytes: Uint8Array): string {
  let binary = '';
  for (const byte of bytes) binary += String.fromCharCode(byte);
  return btoa(binary).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}

/**
 * Generates a new cryptographically secure random QR login token.
 * The raw token is embedded in the QR code URL and returned to the
 * caller exactly once — only its hash (see hashQrLoginToken) is persisted.
 */
export function generateQrLoginToken(): string {
  const cryptoApi = globalThis.crypto;
  if (!cryptoApi?.getRandomValues) {
    throw new Error('Secure random generation is unavailable');
  }

  const bytes = new Uint8Array(TOKEN_BYTES);
  cryptoApi.getRandomValues(bytes);
  return base64UrlEncode(bytes);
}

/**
 * Hashes a raw QR login token with SHA-256 for storage and lookup.
 * See the module doc for why SHA-256 (not bcrypt) is appropriate here.
 *
 * @param token - The raw token to hash
 * @returns A 64-character lowercase hex digest
 */
export async function hashQrLoginToken(token: string): Promise<string> {
  const cryptoApi = globalThis.crypto;
  if (!cryptoApi?.subtle) {
    throw new Error('Secure hashing is unavailable');
  }

  const data = new TextEncoder().encode(token);
  const digest = await cryptoApi.subtle.digest('SHA-256', data);
  return Array.from(new Uint8Array(digest))
    .map((byte) => byte.toString(16).padStart(2, '0'))
    .join('');
}
